build:
  image: framgia/laravel-workspace
  commands:
    - chmod -R 777 storage/
    - chmod -R 777 bootstrap/cache/
    - composer install
    - php artisan migrate --database=mysql_test
    - vendor/bin/phpunit
compose:
  mysql_test:
    image: mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
cache:
  mount:
    - .git
    - vendor
    - node_modules
